# ----------------------------------------------------------------------------
# Copyright (c) 2021-2026 DexForce Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

import torch
from typing import Dict, Optional, Tuple

from embodichain.lab.gym.envs import EmbodiedEnv, EmbodiedEnvCfg
from embodichain.lab.gym.utils.registration import register_env
from embodichain.utils import logger

from embodichain.lab.gym.envs.tasks.tableware.base_agent_env import BaseAgentEnv
from .action_bank import (
    ItemsHandoverPlaceActionBank,
)
__all__ = [
    "ItemsHandoverPlaceEnv",
    "ItemsHandoverPlaceTestEnv",
    "ItemsHandoverPlaceAgentEnv",
]


@register_env("ItemsHandoverPlace-v0", max_episode_steps=600)
class ItemsHandoverPlaceEnv(EmbodiedEnv):
    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)

        action_config = kwargs.get("action_config", None)
        if action_config is not None:
            self.action_config = action_config

    def create_demo_action_list(self, *args, **kwargs):
        """
        Create a demonstration action list for the current task.

        Returns:
            list: A list of demo actions generated by the task.
        """
        logger.log_info("Create demo action list for ItemsHandoverPlaceTask.")

        if getattr(self, "action_config") is not None:
            self._init_action_bank(ItemsHandoverPlaceActionBank, self.action_config)
            action_list = self.create_expert_demo_action_list(*args, **kwargs)
        else:
            logger.log_error("No action_config found in env, please check again.")

        if action_list is None:
            return action_list

        logger.log_info(
            f"Demo action list created with {len(action_list)} steps.", color="green"
        )
        return action_list

    def create_expert_demo_action_list(self, **kwargs):
        """
        Create an expert demonstration action list using the action bank.

        This function generates a trajectory based on expert knowledge, mapping joint and end-effector
        states to the required action format for the environment and robot type.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            list: A list of actions, each containing joint positions ("qpos").
        """

        if hasattr(self, "action_bank") is False or self.action_bank is None:
            logger.log_error(
                "Action bank is not initialized. Cannot create expert demo action list."
            )

        ret = self.action_bank.create_action_list(
            self, self.graph_compose, self.packages
        )

        if ret is None:
            logger.log_warning("Failed to generate expert demo action list.")
            return None

        # TODO: to be removed, need a unified interface in robot class
        left_arm_joints = self.robot.get_joint_ids(name="left_arm", remove_mimic=True)
        right_arm_joints = self.robot.get_joint_ids(name="right_arm", remove_mimic=True)
        left_eef_joints = self.robot.get_joint_ids(name="left_eef", remove_mimic=True)
        right_eef_joints = self.robot.get_joint_ids(name="right_eef", remove_mimic=True)


        total_traj_num = ret[list(ret.keys())[0]].shape[-1]
        num_active_joints = len(self.active_joint_ids)
        actions = torch.zeros(
            (total_traj_num, self.num_envs, num_active_joints), dtype=torch.float32
        )

        # 建立一个从全局 joint_id 到 active_joint_id 在 action 数组中正确存放位置的映射
        global_to_active_idx = {
            joint_id: active_idx for active_idx, joint_id in enumerate(self.active_joint_ids)
        }

        for key, joints in [
            ("left_arm", left_arm_joints),
            ("left_eef", left_eef_joints),
            ("right_arm", right_arm_joints),
            ("right_eef", right_eef_joints),
        ]:
            if key in ret:
                # TODO: only 1 env supported now
                local_action_data = torch.as_tensor(ret[key].T, dtype=torch.float32)

                # 使用映射精准定位它在 action tensor 中的正确位置存放
                for i, joint_id in enumerate(joints):
                    if joint_id in global_to_active_idx:
                        active_idx = global_to_active_idx[joint_id]
                        actions[:, 0, active_idx] = local_action_data[:, i]
        return actions

    def _evaluate_task_state(self) -> Tuple[torch.Tensor, torch.Tensor, Dict]:
        pen = self.sim.get_rigid_object("pen")
        holder = self.sim.get_rigid_object("holder")

        pen_final_xpos = pen.get_local_pose(to_matrix=True)
        holder_final_xpos = holder.get_local_pose(to_matrix=True)

        pen_ret = self._is_fall_x(pen_final_xpos)
        holder_ret = self._is_fall_y(holder_final_xpos)
        pen_pos_xy = pen_final_xpos[:, :2, 3]
        holder_pos_xy = holder_final_xpos[:, :2, 3]

        dist = torch.linalg.norm(pen_pos_xy - holder_pos_xy, dim=-1)
        # print(f"Pen-Holder distance: {dist.item():.4f}")
        dist_threshold = 0.03
        pen_near_holder = dist <= dist_threshold

        success = (~holder_ret) & pen_near_holder & (~pen_ret)
        metrics = {
            "pen_holder_dist": dist,
            "holder_fall": holder_ret,
        }
        return success, holder_ret, metrics

    def is_task_success(self, **kwargs) -> torch.Tensor:
        success, _, _ = self._evaluate_task_state()
        return success

    def _is_fall_x(self, pose: torch.Tensor) -> torch.Tensor:
        # Extract x-axis from rotation matrix (last column, first 3 elements)
        pose_rz = pose[:, :3, 0]
        world_z_axis = torch.tensor([0, 0, 1], dtype=pose.dtype, device=pose.device)

        # Compute dot product for each batch element
        dot_product = torch.sum(pose_rz * world_z_axis, dim=-1)  # Shape: (batch_size,)

        # Clamp to avoid numerical issues with arccos
        dot_product = torch.clamp(dot_product, -1.0, 1.0)

        # Compute angle and check if fallen
        angle = torch.arccos(dot_product)
        return angle >= 1.309 #75度

    def _is_fall_y(self, pose: torch.Tensor) -> torch.Tensor:
        # Extract x-axis from rotation matrix (last column, first 3 elements)
        pose_rz = pose[:, :3, 1]
        world_z_axis = torch.tensor([0, 0, 1], dtype=pose.dtype, device=pose.device)

        # Compute dot product for each batch element
        dot_product = torch.sum(pose_rz * world_z_axis, dim=-1)  # Shape: (batch_size,)

        # Clamp to avoid numerical issues with arccos
        dot_product = torch.clamp(dot_product, -1.0, 1.0)

        # Compute angle and check if fallen
        angle = torch.arccos(dot_product)
        return angle >= 1.309 #75度

@register_env("ItemsHandoverPlaceTest-v0", max_episode_steps=600)
class ItemsHandoverPlaceTestEnv(ItemsHandoverPlaceEnv):
    def compute_task_state(self, **kwargs):
        success, fail, _ = self._evaluate_task_state()
        return torch.zeros_like(fail, dtype=torch.bool), fail, None

    def is_task_success(self, **kwargs) -> torch.Tensor:
        success, _, _ = self._evaluate_task_state()
        return torch.ones_like(success, dtype=torch.bool)

@register_env("ItemsHandoverPlaceAgent-v0", max_episode_steps=600)
class ItemsHandoverPlaceAgentEnv(BaseAgentEnv, ItemsHandoverPlaceEnv):
    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)
        super()._init_agents(**kwargs)

    def reset(self, seed: Optional[int] = None, options: Optional[Dict] = None):
        obs, info = super().reset(seed=seed, options=options)
        super().get_states()
        return obs, info
