# ----------------------------------------------------------------------------
# Copyright (c) 2021-2026 DexForce Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

import os
import torch
import numpy as np
from copy import deepcopy
from typing import Dict, Union, Optional, Sequence, Tuple, List

from embodichain.lab.gym.envs import EmbodiedEnv, EmbodiedEnvCfg
from embodichain.lab.gym.utils.registration import register_env
from .action_bank import (
    RearrangementActionBank,
)
from embodichain.utils import configclass, logger

__all__ = ["RearrangementEnv3Challenge"]


@register_env("RearrangementChallenge-v3")
class RearrangementEnv3Challenge(EmbodiedEnv):
    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)

        action_config = kwargs.get("action_config", None)
        if action_config is not None:
            self.action_config = action_config

    def create_demo_action_list(self, *args, **kwargs):
        """
        Create a demonstration action list for the current task.

        Returns:
            list: A list of demo actions generated by the task.
        """
        logger.log_info("Create demo action list for RTearrangementTask.")

        if getattr(self, "action_config") is not None:
            self._init_action_bank(RearrangementActionBank, self.action_config)
            action_list = self.create_expert_demo_action_list(*args, **kwargs)
        else:
            logger.log_error("No action_config found in env, please check again.")

        if action_list is None:
            return action_list

        logger.log_info(
            f"Demo action list created with {len(action_list)} steps.", color="green"
        )
        return action_list

    def create_expert_demo_action_list(self, **kwargs):
        """
        Create an expert demonstration action list using the action bank.

        This function generates a trajectory based on expert knowledge, mapping joint and end-effector
        states to the required action format for the environment and robot type.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            list: A list of actions, each containing joint positions ("qpos").
        """

        if hasattr(self, "action_bank") is False or self.action_bank is None:
            logger.log_error(
                "Action bank is not initialized. Cannot create expert demo action list."
            )

        ret = self.action_bank.create_action_list(
            self, self.graph_compose, self.packages
        )

        if ret is None:
            logger.log_warning("Failed to generate expert demo action list.")
            return None

        # TODO: to be removed, need a unified interface in robot class
        left_arm_joints = self.robot.get_joint_ids(name="left_arm", remove_mimic=True)
        right_arm_joints = self.robot.get_joint_ids(name="right_arm", remove_mimic=True)
        left_eef_joints = self.robot.get_joint_ids(name="left_eef", remove_mimic=True)
        right_eef_joints = self.robot.get_joint_ids(name="right_eef", remove_mimic=True)


        total_traj_num = ret[list(ret.keys())[0]].shape[-1]
        num_active_joints = len(self.active_joint_ids)
        actions = torch.zeros(
            (total_traj_num, self.num_envs, num_active_joints), dtype=torch.float32
        )

        # 建立一个从全局 joint_id 到 active_joint_id 在 action 数组中正确存放位置的映射
        global_to_active_idx = {
            joint_id: active_idx for active_idx, joint_id in enumerate(self.active_joint_ids)
        }

        for key, joints in [
            ("left_arm", left_arm_joints),
            ("left_eef", left_eef_joints),
            ("right_arm", right_arm_joints),
            ("right_eef", right_eef_joints),
        ]:
            if key in ret:
                # TODO: only 1 env supported now
                local_action_data = torch.as_tensor(ret[key].T, dtype=torch.float32)

                # 【修改重点2】：使用映射精准定位它在 action tensor 中的正确位置存放
                for i, joint_id in enumerate(joints):
                    if joint_id in global_to_active_idx:
                        active_idx = global_to_active_idx[joint_id]
                        actions[:, 0, active_idx] = local_action_data[:, i]
        return actions
    def get_arm_fk(
        self, qpos: np.ndarray, control_part: str, is_world_coordinates=True
    ) -> np.ndarray:
        from embodichain.utils.math import matrix_from_quat

        xpos = self.robot.compute_fk(
            name=control_part, qpos=torch.as_tensor(qpos), to_matrix=True
        ).squeeze(0)

        # the xpos computed from robot is in the local arena frame, which is equivalent to world frame of the
        # old version.
        return xpos.cpu().numpy()

    def get_arm_ik(
        self,
        target_xpos: np.ndarray,
        is_left: bool,
        qpos_seed: np.ndarray = None,
    ) -> Tuple[bool, np.ndarray]:
        from embodichain.utils.math import matrix_from_quat

        xpos = torch.as_tensor(target_xpos, dtype=torch.float32)

        control_part = "left_arm" if is_left else "right_arm"
        ret, qpos = self.robot.compute_ik(
            name=control_part, pose=xpos, joint_seed=torch.as_tensor(qpos_seed)
        )
        return ret.all().item(), qpos.squeeze(0).cpu().numpy()

    def is_task_success(self, *args, **kwargs) -> bool:
        fork = self.sim.get_rigid_object("fork")
        spoon = self.sim.get_rigid_object("spoon")
        plate = self.sim.get_rigid_object("plate")
        plate_pose = plate.get_local_pose(to_matrix=True)

        # Compute target positions from plate pose
        spoon_place_target_y = plate_pose[0, 1, 3] - 0.16
        fork_place_target_y = plate_pose[0, 1, 3] + 0.16

        spoon_pose = spoon.get_local_pose(to_matrix=True)
        spoon_y = spoon_pose[0, 1, 3]

        fork_pose = fork.get_local_pose(to_matrix=True)
        fork_y = fork_pose[0, 1, 3]

        tolerance = self.metadata.get("success_params", {}).get("tolerance", 0.02)

        # spoon and fork should with the y range of tolerance related to plate.
        return (
            abs(spoon_y - spoon_place_target_y) <= tolerance
            and abs(fork_y - fork_place_target_y) <= tolerance
        )
